### ISSUE TITLE
ItemsMap props

### ISSUE THREAD

**Issue by adlogi** [Lebanon-WBC-Capstones/real-generosity-web#127]
This component should have these props:
- whether the map is editable (user can add a marker)
- a list of locations
- a call back to handle adding a marker

**Comment by JosephTarrazi** [comment]
this one is finished. I already have done it while implementing the maps. It just needs to be connected to the database and map over the array of coords.

**Comment by adlogi** [comment]
All data that is to be read from the database should currently be imported from `src/assets/data/` in the proper component. Nothing should be hard-coded. However, this component has no database connection in the first place! If the component is ready, please create an MR for it.
